[workspace]
members = [
    # Public API
    "gymnasium",
    # CLI tool
    "gymnasium_cli",
    # Core library
    "gymnasium_core",
    # Derive macros
    "gymnasium_derive",
    # Python module
    "gymnasium_py",
    # Rust FFI bindings
    "gymnasium_sys",
]
resolver = "2"

[workspace.package]
authors = ["Andrej Orsula <orsula.andrej@gmail.com>"]
categories = ["api-bindings", "science"]
description = "Gymnasium API for Reinforcement Learning"
edition = "2021"
keywords = ["gym", "ml", "rl"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AndrejOrsula/gymnasium_rs"
rust-version = "1.74"
version = "0.0.1"

[workspace.dependencies]
gymnasium = { path = "gymnasium", version = "0.0.1" }
gymnasium_core = { path = "gymnasium_core", version = "0.0.1" }
gymnasium_derive = { path = "gymnasium_derive", version = "0.0.1" }
gymnasium_sys = { path = "gymnasium_sys", version = "0.0.1" }

clap = { version = "4.6", features = ["derive"] }
itertools = { version = "0.15" }
num-traits = { version = "0.2" }
proc-macro2 = { version = "1" }
pyo3 = { version = "0.21" }
pyo3_bindgen = { version = "0.5", features = ["numpy"] }
quote = { version = "1" }
rand = { version = "0.9", features = ["small_rng"] }
syn = { version = "2" }
thiserror = { version = "2.0" }

candle-core = { version = "0.10" }
dfdx = { version = "0.13" }
ndarray = { version = "0.17" }
numpy = { version = "0.21" }

# assert_cmd = { version = "2" }
# predicates = { version = "3" }
# rustc-hash = { version = "1" }

[patch.crates-io]
# pyo3_bindgen = { path = "../pyo3_bindgen/pyo3_bindgen" }
