[package]
name = "gymnasium_core"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gymnasium_sys = { workspace = true }

itertools = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
ndarray = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true }
numpy = { workspace = true, optional = true }

candle-core = { workspace = true, optional = true }
dfdx = { workspace = true, optional = true }

[features]
# TODO: Remove some of the default features. Maybe move them all to the public API crate
default = ["candle", "ndarray", "numpy", "python"]
python = ["dep:pyo3"]
ndarray = ["dep:ndarray"]
# dfdx = ["dep:dfdx"]
candle = ["dep:candle-core"]
numpy = ["dep:numpy"]
