[package]
name = "gymnasium"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gymnasium_core = { workspace = true }
gymnasium_derive = { workspace = true, optional = true }

# pyo3 = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
# TODO: Remove derive feature from defaults
# TODO: Add features from underlying crates
default = ["derive"]
derive = ["dep:gymnasium_derive"]
# python = ["dep:pyo3"]

[package.metadata.docs.rs]
all-features = true
